export const UPLOAD_SINGLE_IMAGE_REQUEST = 'UPLOAD_SINGLE_IMAGE_REQUEST';
export const UPLOAD_SINGLE_IMAGE_SUCCESS = 'UPLOAD_SINGLE_IMAGE_SUCCESS';
export const UPLOAD_SINGLE_IMAGE_FAIL = 'UPLOAD_SINGLE_IMAGE_FAIL';
export const UPLOAD_SINGLE_IMAGE_RESET = 'UPLOAD_SINGLE_IMAGE_RESET';
