export const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirts',
      category: 'Shirts',
      image: './images/p1.jpg',
      price: 120,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Addidas Slim Shirts',
      category: 'Shirts',
      image: './images/p2.jpg',
      price: 130,
      countInStock: 1,
      brand: 'Addidas',
      rating: 4,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Lacosta Slim Shirts',
      category: 'Shirts',
      image: './images/p3.jpg',
      price: 120,
      countInStock: 0,
      brand: 'Lacosta',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Nike Slim Pants',
      category: 'Pants',
      image: './images/p4.jpg',
      price: 138,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Puma Slim Pants',
      category: 'Pants',
      image: './images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Addidas Fit Pants',
      category: 'Pants',
      image: './images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
